// this script is intended to ingest the database with all the data in the dataset folder
const mysql = require('mysql2')
const xlsx = require('xlsx')
const path = require('path')
/*
  data layout - categories of entries: first Izvajalec, then Dejavnost, Zdravnik and finally Zaposlitev_zdravnika
  GIN_ZO - gynecologist
  SA_ZO - primary care/family doctor
  ZOB_ZO - dentist
  data structure:
    - Izvajalec: sifra_iz, naziv_iz, enota, ulica, kraj -> B, C, A, D, E
    - Dejavnost: sifra_de, naziv_de -> H, I
    - Zdravnik: sifra_zd, ime, sifra_de, sifra_iz -> F, G, H, I
    - Zaposlitev_zdravnika: id_zapos, sifra_zd, datum, obseg, kolicnik, sprejem -> _, F, _, K, L, J
        -- (first _ is generated by the DB, second _ is parsed from the file date)
*/

// function that takes a filename and does
function ingestFile(filePath) {

  file = path.basename(filePath, path.extname(filePath));

  // prepare the query strings and arrays of rows
  var queryIzvajalec = `INSERT IGNORE INTO Izvajalec VALUES ?`;
  var queryDejavnost = `INSERT IGNORE INTO Dejavnost VALUES ?`;
  var queryZdravnik = `INSERT IGNORE INTO Zdravnik VALUES ?`;
  var queryZaposlitevZdravnika = `INSERT IGNORE INTO Zaposlitev_zdravnika VALUES ?`;
  var valuesIzvajalec = [];
  var valuesDejavnost = [];
  var valuesZdravnik = [];
  var valuesZaposlitevZdravnika = [];

  // access the sheet
  const workbook = xlsx.readFile(file);
  const sheetName = workbook.SheetNames[0];
  const sheet = workbook.Sheets[sheetName];

  // extract the rows
  const rows = xlsx.utils.sheet_to_json(sheet, { header: 1 }).slice(10);

  // iterate through them
  for (let row of rows) {

    if (row.slice(0, 12).some(val => val === "")) return; // data integrity (A-L columns contain the data)

    valuesIzvajalec.push([parseInt(row[1]), row[2], row[0], row[3], row[4]]);
    valuesDejavnost.push([parseInt(row[7]), row[8]]);
    valuesZdravnik.push([row[5], row[6], row[7], row[8]]);
    
    // FINISH THIS
  }
}
// try connecting to db
try {
    const conn = await mysql.createConnection({
      host: process.env.DB_HOST,
      user: process.env.DB_USER,
      password: process.env.DB_PASS,
      database: process.env.DB_DATABASE,
    });
    console.log('Connection established');
    return conn;
  } catch (err) {
    console.error('ERROR:', err.message);
    process.exit(1);
  }

// main loop
// iterate through folders, for each file named correctly run ingestFile

